import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import GetConfiguration from '@/lib/GetConfiguration'
import { Configuration } from '@/types'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Innoloft',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  
  
}: {
  children: React.ReactNode
  
}) {
  const config: Promise<Configuration> = await GetConfiguration()
  
  console.log('config',config)
  
  return (
    <html lang="en">
      
      <body className='bg-slate-100'>
      <Navbar id={(await config).id}
      logo={(await config).logo}
      hasUserSection={(await config).hasUserSection}
      mainColor={(await config).mainColor}
      />
      <div className=''>
        
        {children}
      </div>
      </body>
    </html>
  )
}
